/**
 * PLAYER_NAME_HE
 * English → Hebrew transliteration of FIFA World Cup 2026 player names.
 * Conventions follow Israeli sports media: ynet, sport5, walla sport, sport1/maariv.
 *
 * Groups (confirmed draw, December 2025):
 *   A: Mexico, South Korea, South Africa, Czech Republic
 *   B: Canada, Bosnia-Herzegovina, Qatar, Switzerland
 *   C: Brazil, Morocco, Scotland, Haiti
 *   D: USA, Australia, Paraguay, Turkey
 *   E: Germany, Ecuador, Ivory Coast, Curaçao
 *   F: Netherlands, Japan, Sweden, Tunisia
 *   G: Belgium, Iran, Egypt, New Zealand
 *   H: Spain, Saudi Arabia, Uruguay, Cape Verde
 *   I: France, Senegal, Norway, Iraq
 *   J: Argentina, Algeria, Austria, Jordan
 *   K: Portugal, Uzbekistan, Colombia, DR Congo
 *   L: England, Croatia, Ghana, Panama
 */

export const PLAYER_NAME_HE = {

  // ── FRANCE (Group I) ────────────────────────────────────────────────────────
  "Kylian Mbappé":            "קיליאן אמבפה",
  "Kylian Mbappe":            "קיליאן אמבפה",
  "Mike Maignan":             "מייק מניאן",
  "Brice Samba":              "בריס סמבה",
  "Robin Risser":             "רובן ריסר",
  "Lucas Digne":              "לוקאס דיניה",
  "Malo Gusto":               "מאלו גוסטו",
  "Lucas Hernandez":          "לוקאס הרננדס",
  "Theo Hernandez":           "תיאו הרננדס",
  "Ibrahima Konaté":          "איברהימה קונאטה",
  "Ibrahima Konate":          "איברהימה קונאטה",
  "Jules Koundé":             "ז'ול קונדה",
  "Jules Kounde":             "ז'ול קונדה",
  "Maxence Lacroix":          "מקסנס לקרואה",
  "William Saliba":           "ויליאם סאליבה",
  "Dayot Upamecano":          "דיו אופמקאנו",
  "N'Golo Kanté":             "נגולו קנטה",
  "N'Golo Kante":             "נגולו קנטה",
  "Manu Koné":                "מנו קונה",
  "Manu Kone":                "מנו קונה",
  "Adrien Rabiot":            "אדריאן ראביו",
  "Aurélien Tchouaméni":      "אורליאן טשואמני",
  "Aurelien Tchouameni":      "אורליאן טשואמני",
  "Warren Zaïre-Emery":       "וורן זייר-אמרי",
  "Warren Zaire-Emery":       "וורן זייר-אמרי",
  "Maghnes Akliouche":        "מאנס אקליוש",
  "Bradley Barcola":          "בראדלי ברקולה",
  "Rayan Cherki":             "ריאן שרקי",
  "Ousmane Dembélé":          "עוסמאן דמבלה",
  "Ousmane Dembele":          "עוסמאן דמבלה",
  "Désiré Doué":              "דזירה דואה",
  "Desire Doue":              "דזירה דואה",
  "Jean-Philippe Mateta":     "ז'אן-פיליפ מאטטה",
  "Michael Olise":            "מייקל אוליס",
  "Marcus Thuram":            "מרקוס תוראם",
  "Antoine Griezmann":        "אנטואן גריזמן",

  // ── SPAIN (Group H) ─────────────────────────────────────────────────────────
  "Lamine Yamal":             "למין ימאל",
  "Unai Simón":               "אונאי סימון",
  "Unai Simon":               "אונאי סימון",
  "David Raya":               "דיוויד ראיה",
  "Joan García":              "ז'ואן גרסיה",
  "Joan Garcia":              "ז'ואן גרסיה",
  "Marc Cucurella":           "מארק קוקורלה",
  "Alejandro Grimaldo":       "אלחנדרו גרימלדו",
  "Alex Grimaldo":            "אלחנדרו גרימלדו",
  "Pau Cubarsí":              "פאו קובארסי",
  "Pau Cubarsi":              "פאו קובארסי",
  "Aymeric Laporte":          "איימריק לאפורט",
  "Marc Pubill":              "מארק פוביל",
  "Eric García":              "אריק גרסיה",
  "Eric Garcia":              "אריק גרסיה",
  "Marcos Llorente":          "מרקוס יורנטה",
  "Pedro Porro":              "פדרו פורו",
  "Pedri":                    "פדרי",
  "Fabián Ruiz":              "פביאן רואיס",
  "Fabian Ruiz":              "פביאן רואיס",
  "Martín Zubimendi":         "מרטין זובימנדי",
  "Martin Zubimendi":         "מרטין זובימנדי",
  "Gavi":                     "גאבי",
  "Rodri":                    "רודרי",
  "Álex Baena":               "אלקס באינה",
  "Alex Baena":               "אלקס באינה",
  "Mikel Merino":             "מיקל מרינו",
  "Mikel Oyarzabal":          "מיקל אויארסבאל",
  "Dani Olmo":                "דאני אולמו",
  "Nico Williams":            "ניקו ויליאמס",
  "Yeremy Pino":              "ירמי פינו",

  // ── ENGLAND (Group L) ───────────────────────────────────────────────────────
  "Harry Kane":               "הארי קיין",
  "Jordan Pickford":          "ג'ורדן פיקפורד",
  "Dean Henderson":           "דין הנדרסון",
  "James Trafford":           "ג'יימס טראפורד",
  "Jude Bellingham":          "ג'וד בלינגהאם",
  "Bukayo Saka":              "בוקאיו סאקה",
  "Declan Rice":              "דקלן רייס",
  "John Stones":              "ג'ון סטונס",
  "Marcus Rashford":          "מרקוס ראשפורד",
  "Phil Foden":               "פיל פודן",
  "Kyle Walker":              "קייל ווקר",
  "Reece James":              "ריס ג'יימס",
  "Marc Guéhi":               "מארק גואי",
  "Marc Guehi":               "מארק גואי",
  "Trent Alexander-Arnold":   "טרנט אלכסנדר-ארנולד",
  "Kobbie Mainoo":            "קובי מיינו",
  "Eberechi Eze":             "אברצ'י אז",
  "Anthony Gordon":           "אנתוני גורדון",
  "Ollie Watkins":            "אולי ווטקינס",
  "Ivan Toney":               "איוון טוני",
  "Noni Madueke":             "נוני מדואקה",
  "Elliot Anderson":          "אליוט אנדרסון",
  "Morgan Rogers":            "מורגן רוג'רס",
  "Ezri Konsa":               "אזרי קונסה",
  "Tino Livramento":          "טינו ליברמנטו",
  "Dan Burn":                 "דאן ברן",
  "Djed Spence":              "ג'ד ספנס",
  "Jarell Quansah":           "ג'ארל קוונסה",
  "Nico O'Reilly":            "ניקו או'ריילי",
  "Jordan Henderson":         "ג'ורדן הנדרסון",

  // ── GERMANY (Group E) ───────────────────────────────────────────────────────
  "Manuel Neuer":             "מנואל נוייר",
  "Oliver Baumann":           "אוליבר באומן",
  "Alexander Nübel":          "אלכסנדר ניובל",
  "Alexander Nubel":          "אלכסנדר ניובל",
  "Joshua Kimmich":           "יהושואה קימיך",
  "Antonio Rüdiger":          "אנטוניו רודיגר",
  "Antonio Rudiger":          "אנטוניו רודיגר",
  "David Raum":               "דיוויד ראום",
  "Nico Schlotterbeck":       "ניקו שלוטרבק",
  "Jonathan Tah":             "יונתן טא",
  "Waldemar Anton":           "ולדמר אנטון",
  "Nathaniel Brown":          "נתניאל בראון",
  "Malick Thiaw":             "מאליק תיאו",
  "Jamal Musiala":            "ג'מאל מוזיאלה",
  "Florian Wirtz":            "פלוריאן וירץ",
  "Leroy Sané":               "לרואה זאנה",
  "Leroy Sane":               "לרואה זאנה",
  "Kai Havertz":              "קאי האוורץ",
  "Leon Goretzka":            "ליאון גורצקה",
  "Pascal Groß":              "פסקל גרוס",
  "Pascal Gross":             "פסקל גרוס",
  "Jamie Leweling":           "ג'יימי לולינג",
  "Nadiem Amiri":             "נאדים אמירי",
  "Assan Ouédraogo":          "אסאן אודראוגו",
  "Assan Ouedraogo":          "אסאן אודראוגו",
  "Felix Nmecha":             "פליקס נמצ'ה",
  "Alexander Pavlovic":       "אלכסנדר פאבלוביץ",
  "Angelo Stiller":           "אנג'לו שטילר",
  "Maximilian Beier":         "מקסימיליאן ביאר",
  "Denis Undav":              "דניס אונדב",
  "Nick Woltemade":           "ניק וולטמאדה",

  // ── BRAZIL (Group C) ────────────────────────────────────────────────────────
  "Alisson":                  "אליסון",
  "Alisson Becker":           "אליסון",
  "Ederson":                  "אדרסון",
  "Vinícius Júnior":          "ויניסיוס ג'וניור",
  "Vinicius Junior":          "ויניסיוס ג'וניור",
  "Raphinha":                 "ראפיניה",
  "Neymar":                   "ניימאר",
  "Neymar Jr":                "ניימאר",
  "Endrick":                  "אנדריק",
  "Gabriel Martinelli":       "גבריאל מרטינלי",
  "Marquinhos":               "מרקיניוס",
  "Casemiro":                 "קאסמירו",
  "Bruno Guimarães":          "ברונו גימרייש",
  "Bruno Guimaraes":          "ברונו גימרייש",
  "Lucas Paquetá":            "לוקאס פאקטה",
  "Lucas Paqueta":            "לוקאס פאקטה",
  "Danilo":                   "דנילו",
  "Gabriel Magalhães":        "גבריאל מגאלייש",
  "Gabriel Magalhaes":        "גבריאל מגאלייש",
  "Matheus Cunha":            "מתאוס קוניה",
  "Luiz Henrique":            "לואיז הנריקה",
  "Igor Thiago":              "איגור תיאגו",
  "Rayan":                    "ריאן",
  "Alex Sandro":              "אלקס סנדרו",
  "Douglas Santos":           "דוגלס סנטוס",
  "Léo Pereira":              "לאו פריירה",
  "Leo Pereira":              "לאו פריירה",
  "Bremer":                   "ברמר",
  "Ibañez":                   "איבניז",
  "Danilo Santos":            "דנילו סנטוס",
  "Fabinho":                  "פביניו",

  // ── ARGENTINA (Group J) ─────────────────────────────────────────────────────
  "Lionel Messi":             "ליונל מסי",
  "Emiliano Martínez":        "אמיליאנו מרטינז",
  "Emiliano Martinez":        "אמיליאנו מרטינז",
  "Juan Musso":               "חואן מוסו",
  "Gerónimo Rulli":           "חרונימו רולי",
  "Geronimo Rulli":           "חרונימו רולי",
  "Gonzalo Montiel":          "גונסאלו מונטייל",
  "Nahuel Molina":            "נאואל מולינה",
  "Lisandro Martínez":        "ליסנדרו מרטינז",
  "Lisandro Martinez":        "ליסנדרו מרטינז",
  "Nicolás Otamendi":         "ניקולאס אוטמנדי",
  "Nicolas Otamendi":         "ניקולאס אוטמנדי",
  "Cristian Romero":          "כריסטיאן רומרו",
  "Facundo Medina":           "פקונדו מדינה",
  "Nicolás Tagliafico":       "ניקולאס טאיאפיקו",
  "Nicolas Tagliafico":       "ניקולאס טאיאפיקו",
  "Leandro Paredes":          "ליאנדרו פארדס",
  "Rodrigo De Paul":          "רודריגו דה פול",
  "Exequiel Palacios":        "אקסקיל פלאסיוס",
  "Enzo Fernández":           "אנסו פרנאנדס",
  "Enzo Fernandez":           "אנסו פרנאנדס",
  "Alexis Mac Allister":      "אלקסיס מק אליסטר",
  "Giovani Lo Celso":         "ג'יובאני לו צ'לסו",
  "Valentín Barco":           "ואלנטין ברקו",
  "Valentin Barco":           "ואלנטין ברקו",
  "Julián Álvarez":           "חוליאן אלווארז",
  "Julian Alvarez":           "חוליאן אלווארז",
  "Lautaro Martínez":         "לאוטרו מרטינז",
  "Lautaro Martinez":         "לאוטרו מרטינז",
  "Nicolás Paz":              "ניקולאס פאס",
  "Nicolas Paz":              "ניקולאס פאס",
  "Thiago Almada":            "תיאגו אלמאדה",
  "Nicolás González":         "ניקולאס גונסאלס",
  "Nicolas Gonzalez":         "ניקולאס גונסאלס",
  "Giuliano Simeone":         "ג'וליאנו סימאונה",
  "José Manuel López":        "חוזה מנואל לופס",
  "Nico Williams":            "ניקו ויליאמס",

  // ── PORTUGAL (Group K) ──────────────────────────────────────────────────────
  "Cristiano Ronaldo":        "כריסטיאנו רונאלדו",
  "Diogo Costa":              "דיוגו קוסטה",
  "Rui Silva":                "רואי סילבה",
  "José Sá":                  "חוזה סה",
  "Ricardo Velho":            "ריקארדו ולו",
  "Rúben Dias":               "רובן דיאס",
  "Ruben Dias":               "רובן דיאס",
  "Gonçalo Inácio":           "גונסאלו אינאסיו",
  "Goncalo Inacio":           "גונסאלו אינאסיו",
  "João Cancelo":             "ז'ואאו קנסלו",
  "Joao Cancelo":             "ז'ואאו קנסלו",
  "Nuno Mendes":              "נונו מנדס",
  "Diogo Dalot":              "דיוגו דאלוט",
  "Nélson Semedo":            "נלסון סמדו",
  "Nelson Semedo":            "נלסון סמדו",
  "Tomás Araújo":             "תומאס אראוחו",
  "Tomas Araujo":             "תומאס אראוחו",
  "Renato Veiga":             "רנאטו וייגה",
  "Vitinha":                  "ויטיניה",
  "João Neves":               "ז'ואאו נבס",
  "Joao Neves":               "ז'ואאו נבס",
  "Bruno Fernandes":          "ברונו פרנאנדס",
  "Rúben Neves":              "רובן נבס",
  "Ruben Neves":              "רובן נבס",
  "Matheus Nunes":            "מתאוס נונס",
  "Samú Costa":               "סאמו קוסטה",
  "Samu Costa":               "סאמו קוסטה",
  "Bernardo Silva":           "ברנרדו סילבה",
  "João Félix":               "ז'ואאו פליקס",
  "Joao Felix":               "ז'ואאו פליקס",
  "Francisco Trincão":        "פרנסיסקו טרינקאו",
  "Francisco Trincao":        "פרנסיסקו טרינקאו",
  "Francisco Conceição":      "פרנסיסקו קונסיסאו",
  "Francisco Conceicao":      "פרנסיסקו קונסיסאו",
  "Pedro Neto":               "פדרו נטו",
  "Rafael Leão":              "ראפאל לאאו",
  "Rafael Leao":              "ראפאל לאאו",
  "Gonçalo Guedes":           "גונסאלו גדס",
  "Goncalo Guedes":           "גונסאלו גדס",
  "Gonçalo Ramos":            "גונסאלו ראמוס",
  "Goncalo Ramos":            "גונסאלו ראמוס",

  // ── NETHERLANDS (Group F) ───────────────────────────────────────────────────
  "Virgil van Dijk":          "וירג'יל ון דייק",
  "Mark Flekken":             "מארק פלקן",
  "Bart Verbruggen":          "בארט ורברוגן",
  "Robin Roefs":              "רובין רופס",
  "Nathan Aké":               "נתן אקה",
  "Nathan Ake":               "נתן אקה",
  "Denzel Dumfries":          "דנזל דמפריס",
  "Jorrel Hato":              "יורל האטו",
  "Jurriën Timber":           "יוריאן טימבר",
  "Jurrien Timber":           "יוריאן טימבר",
  "Micky van de Ven":         "מיקי ון דה וון",
  "Jan Paul van Hecke":       "יאן פול ון הקה",
  "Mats Wieffer":             "מאטס ויפר",
  "Frenkie de Jong":          "פרנקי דה יונג",
  "Marten de Roon":           "מרטן דה רון",
  "Ryan Gravenberch":         "ריאן גראונברג",
  "Justin Kluivert":          "יוסטין קלוברט",
  "Teun Koopmeiners":         "טון קופמיינרס",
  "Tijjani Reijnders":        "טיג'אני ריינדרס",
  "Guus Til":                 "גוס טיל",
  "Quinten Timber":           "קווינטן טימבר",
  "Brian Brobbey":            "בריאן ברובי",
  "Memphis Depay":            "ממפיס דפאי",
  "Cody Gakpo":               "קודי גאקפו",
  "Noa Lang":                 "נוא לנג",
  "Donyell Malen":            "דוניל מאלן",
  "Crysencio Summerville":    "קריסנציו סמרוויל",
  "Wout Weghorst":            "וות ווגהורסט",
  "Kevin De Bruyne":          "קווין דה ברויינה",

  // ── BELGIUM (Group G) ───────────────────────────────────────────────────────
  "Thibaut Courtois":         "טיבו קורטואה",
  "Senne Lammens":            "סנה למנס",
  "Mike Penders":             "מייק פנדרס",
  "Timothy Castagne":         "טימותי קסטאן",
  "Zeno Debast":              "זנו דבאסט",
  "Maxim De Cuyper":          "מקסים דה קויפר",
  "Koni De Winter":           "קוני דה ווינטר",
  "Brandon Mechele":          "ברנדון מכלה",
  "Thomas Meunier":           "תומס מוניה",
  "Nathan Ngoy":              "נתן נגוי",
  "Arthur Theate":            "ארתור טהאט",
  "Amadou Onana":             "אמאדו אונאנה",
  "Nicolas Raskin":           "ניקולא ראסקן",
  "Youri Tielemans":          "יורי טילמנס",
  "Hans Vanaken":             "האנס וונאקן",
  "Axel Witsel":              "אקסל ויטסל",
  "Kevin De Bruyne":          "קווין דה ברויינה",
  "Romelu Lukaku":            "רומלו לוקאקו",
  "Charles De Ketelaere":     "שארל דה קטלרה",
  "Jeremy Doku":              "ג'רמי דוקו",
  "Matias Fernandez-Pardo":   "מאטיאס פרנאנדס-פרדו",
  "Dodi Lukebakio":           "דודי לוקבאקיו",
  "Diego Moreira":            "דיאגו מוראירה",
  "Alexis Saelemaekers":      "אלקסיס סלמייקרס",
  "Leandro Trossard":         "ליאנדרו טרוסאר",

  // ── CROATIA (Group L) ───────────────────────────────────────────────────────
  "Luka Modrić":              "לוקה מודריץ",
  "Luka Modric":              "לוקה מודריץ",
  "Mateo Kovačić":            "מאטאו קובאצ'יץ",
  "Mateo Kovacic":            "מאטאו קובאצ'יץ",
  "Ivan Perišić":             "איוון פריסיץ",
  "Ivan Perisic":             "איוון פריסיץ",
  "Andrej Kramarić":          "אנדרי קרמאריץ",
  "Andrej Kramaric":          "אנדרי קרמאריץ",
  "Dominik Livaković":        "דומיניק ליבאקוביץ",
  "Dominik Livakovic":        "דומיניק ליבאקוביץ",
  "Joško Gvardiol":           "יושקו גווארדיול",
  "Josko Gvardiol":           "יושקו גווארדיול",
  "Duje Ćaleta-Car":          "דואה קאלטה-קאר",
  "Duje Caleta-Car":          "דואה קאלטה-קאר",
  "Marin Pongračić":          "מרין פונגרציץ",
  "Marin Pongracic":          "מרין פונגרציץ",
  "Josip Juranović":          "יוסיפ יורנוביץ",
  "Josip Juranovic":          "יוסיפ יורנוביץ",
  "Borna Stanišić":           "בורנה סטניסיץ",
  "Borna Stanisic":           "בורנה סטניסיץ",
  "Mario Pašalić":            "מריו פאשאליץ",
  "Mario Pasalic":            "מריו פאשאליץ",
  "Nikola Vlašić":            "ניקולה ולאסיץ",
  "Nikola Vlasic":            "ניקולה ולאסיץ",
  "Luka Sučić":               "לוקה סוציץ",
  "Luka Sucic":               "לוקה סוציץ",
  "Martin Baturina":          "מרטין בטורינה",
  "Petar Sučić":              "פטר סוציץ",
  "Petar Sucic":              "פטר סוציץ",
  "Ante Budimir":             "אנטה בודימיר",

  // ── MOROCCO (Group C) ───────────────────────────────────────────────────────
  "Yassine Bounou":           "יסין בונו",
  "Munir Mohamedi":           "מוניר מוחמדי",
  "Achraf Hakimi":            "אשרף חכימי",
  "Sofyan Amrabat":           "סופיאן אמראבאט",
  "Hakim Ziyech":             "חכים זיאש",
  "Brahim Díaz":              "ברהים דיאס",
  "Brahim Diaz":              "ברהים דיאס",
  "Romain Saïss":             "רומן סייס",
  "Romain Saiss":             "רומן סייס",
  "Nayef Aguerd":             "נאיף אגרד",
  "Yahya Attiat-Allah":       "יחיא עטיאת אל-אאה",
  "Noussair Mazraoui":        "נוסייר מזראואי",
  "Aziz Bouhaddouz":          "עזיז בוחדוז",
  "Ilias Chair":              "אליאס שיר",
  "Sofiane Boufal":           "סופיאן בופאל",
  "Amine Harit":              "אמין חריט",
  "Tarik Tissoudali":         "טריק טיסודאלי",
  "Selim Amallah":            "סלים אמאלה",
  "Amine Sbai":               "אמין סבאי",

  // ── SENEGAL (Group I) ───────────────────────────────────────────────────────
  "Sadio Mané":               "סאדיו מאנה",
  "Sadio Mane":               "סאדיו מאנה",
  "Édouard Mendy":            "אדואר מנדי",
  "Edouard Mendy":            "אדואר מנדי",
  "Kalidou Koulibaly":        "קאלידו קוליבאלי",
  "Nicolas Jackson":          "ניקולס ג'קסון",
  "Pape Matar Sarr":          "פאפה מאטר סאר",
  "Idrissa Gana Gueye":       "אידריסה גאנה גואיה",
  "Iliman Ndiaye":            "אלימן נדיאי",
  "Ismaila Sarr":             "ישמעיל סאר",
  "Krepin Diatta":            "קרפן דיאטה",
  "Lamine Camara":            "למין קמרה",
  "El Hadji Malick Diouf":    "אל האד'ג' מאליק דיוף",
  "Pape Gueye":               "פאפה גואיה",
  "Moussa Niakhate":          "מוסה ניאכאטה",
  "Ismail Jakobs":            "ישמעיל ג'אקובס",
  "Mamadou Sarr":             "ממאדו סאר",
  "Mory Diaw":                "מורי דיאו",
  "Yehvann Diouf":            "יהווין דיוף",
  "Bamba Dieng":              "במבה דינג",
  "Assane Diao":              "אסאן דיאו",

  // ── MEXICO (Group A) ────────────────────────────────────────────────────────
  "Guillermo Ochoa":          "גיירמו אוצ'וה",
  "Edson Álvarez":            "אדסון אלווארס",
  "Edson Alvarez":            "אדסון אלווארס",
  "Santiago Giménez":         "סנטיאגו חימנס",
  "Santiago Gimenez":         "סנטיאגו חימנס",
  "Raúl Jiménez":             "ראול חימנס",
  "Raul Jimenez":             "ראול חימנס",
  "Hirving Lozano":           "אירבינג לוסאנו",
  "César Montes":             "סזאר מונטס",
  "Cesar Montes":             "סזאר מונטס",
  "Johan Vásquez":            "יוהאן ואסקס",
  "Johan Vasquez":            "יוהאן ואסקס",
  "Orbelín Pineda":           "אורבלין פינדה",
  "Orbelin Pineda":           "אורבלין פינדה",
  "Alexis Vega":              "אלקסיס ווגה",
  "Roberto Alvarado":         "רוברטו אלווארדו",
  "Luis Chávez":              "לואיס שאבס",
  "Luis Chavez":              "לואיס שאבס",
  "Álvaro Fidalgo":           "אלווארו פידאלגו",
  "Alvaro Fidalgo":           "אלווארו פידאלגו",
  "Brian Gutiérrez":          "בריאן גוטיירס",
  "Brian Gutierrez":          "בריאן גוטיירס",
  "Gilberto Mora":            "חילברטו מורה",
  "Julián Quiñones":          "חוליאן קיניונס",
  "Julian Quinones":          "חוליאן קיניונס",
  "Jesús Gallardo":           "חסוס גאיארדו",
  "Jesus Gallardo":           "חסוס גאיארדו",
  "Erik Lira":                "אריק לירה",
  "Israel Reyes":             "ישראל ריס",
  "Jorge Sánchez":            "חורחה סנצ'ס",
  "Jorge Sanchez":            "חורחה סנצ'ס",

  // ── UNITED STATES (Group D) ─────────────────────────────────────────────────
  "Christian Pulisic":        "כריסטיאן פוליסיץ",
  "Tyler Adams":              "טיילר אדמס",
  "Weston McKennie":          "ווסטון מקני",
  "Gio Reyna":                "ג'יו ריינה",
  "Giovanni Reyna":           "ג'ובאני ריינה",
  "Matt Turner":              "מאט טרנר",
  "Chris Brady":              "כריס בריידי",
  "Matt Freese":              "מאט פריז",
  "Sergiño Dest":             "סרג'ינו דסט",
  "Sergino Dest":             "סרג'ינו דסט",
  "Tim Ream":                 "טים רים",
  "Chris Richards":           "כריס ריצ'ארדס",
  "Antonee Robinson":         "אנטוני רובינסון",
  "Miles Robinson":           "מיילס רובינסון",
  "Joe Scally":               "ג'ו סקאלי",
  "Auston Trusty":            "אוסטון טרסטי",
  "Mark McKenzie":            "מארק מקנזי",
  "Max Arfsten":              "מקס ארפסטן",
  "Alex Freeman":             "אלקס פרימן",
  "Cristian Roldan":          "כריסטיאן רולדן",
  "Malik Tillman":            "מאליק טילמן",
  "Sebastian Berhalter":      "סבסטיאן ברהאלטר",
  "Folarin Balogun":          "פולארין באלוגון",
  "Ricardo Pepi":             "ריקארדו פפי",
  "Brenden Aaronson":         "ברנדן אהרונסון",
  "Tim Weah":                 "טים ווה",
  "Haji Wright":              "האג'י רייט",
  "Alex Zendejas":            "אלקס זנדחאס",

  // ── CANADA (Group B) ────────────────────────────────────────────────────────
  "Alphonso Davies":          "אלפונסו דיוויס",
  "Jonathan David":           "ג'ונתן דיוויד",
  "Cyle Larin":               "סייל לארין",
  "Maxime Crépeau":           "מקסים קרפו",
  "Maxime Crepeau":           "מקסים קרפו",
  "Dayne St. Clair":          "דיין סנט קלייר",
  "Owen Goodman":             "אוון גודמן",
  "Alistair Johnston":        "אליסטר ג'ונסטון",
  "Kamal Miller":             "קמל מילר",
  "Steven Vitória":           "סטיבן ויטוריה",
  "Steven Vitoria":           "סטיבן ויטוריה",
  "Derek Cornelius":          "דרק קורנליוס",
  "Richie Laryea":            "ריצ'י לריאה",
  "Liam Millar":              "ליאם מילר",
  "Ismaël Koné":              "ישמעיל קונה",
  "Ismael Kone":              "ישמעיל קונה",
  "Stephen Eustaquio":        "סטיבן אוסטאקיו",
  "Tajon Buchanan":           "טאג'ון בוקנן",
  "Mark-Anthony Kaye":        "מארק-אנתוני קיי",
  "Tani Oluwaseyi":           "טאני אולוואסיי",
  "Promise David":            "פרומיס דיוויד",
  "Jayden Nelson":            "ג'יידן נלסון",
  "Junior Hoilett":           "ג'וניור הויולט",
  "Sam Adekugbe":             "סם אדקוגבה",

  // ── AUSTRALIA (Group D) ─────────────────────────────────────────────────────
  "Mathew Ryan":              "מתיו ריאן",
  "Mat Ryan":                 "מתיו ריאן",
  "Aaron Mooy":               "אהרון מואי",
  "Mitchell Duke":            "מיצ'ל דיוק",
  "Jackson Irvine":           "ג'קסון אירווין",
  "Ajdin Hrustic":            "אג'דין חרוסטיץ",
  "Martin Boyle":             "מרטין בויל",
  "Jason Cummings":           "ג'ייסון קאמינגס",
  "Harry Souttar":            "הארי סאוטאר",
  "Milos Degenek":            "מילוש דגנק",
  "Aziz Behich":              "עזיז בהיץ'",
  "Craig Goodwin":            "קרייג גודווין",
  "Awer Mabil":               "עוור מביל",
  "Tom Rogic":                "טום רוגיץ",
  "Ben Folami":               "בן פולאמי",

  // ── JAPAN (Group F) ─────────────────────────────────────────────────────────
  "Takefusa Kubo":            "טאקפוסה קובו",
  "Ritsu Doan":               "ריצו דואן",
  "Daichi Kamada":            "דאיצ'י קמאדה",
  "Ao Tanaka":                "אאו טנאקה",
  "Ko Itakura":               "קו איטאקורה",
  "Hiroki Ito":               "הירוקי איטו",
  "Yuto Nagatomo":            "יוטו נגטומו",
  "Takehiro Tomiyasu":        "טקהירו טומיאסו",
  "Keito Nakamura":           "קייטו נקמורה",
  "Ayase Ueda":               "איאסה אואדה",
  "Junya Ito":                "ג'וניה איטו",
  "Yukinari Sugawara":        "יוקינרי סוגוורה",
  "Ayumu Seko":               "איומו סקו",
  "Daizen Maeda":             "דייזן מאדה",
  "Koki Ogawa":               "קוקי אוגוה",
  "Kaishu Sano":              "קייסו סאנו",
  "Shogo Taniguchi":          "שוגו טניגוצ'י",
  "Tsuyoshi Watanabe":        "צויושי ווטנאבה",
  "Junnosuke Suzuki":         "ג'ונוסוקה סוזוקי",
  "Machino Shūto":            "מצ'ינו שוטו",
  "Shuuto Machino":           "שוטו מצ'ינו",

  // ── SOUTH KOREA (Group A) ───────────────────────────────────────────────────
  "Son Heung-min":            "סון הון-מין",
  "Kim Min-jae":              "קים מין-ג'ה",
  "Lee Kang-in":              "לי קנג-אין",
  "Cho Gue-sung":             "צ'ו גה-סונג",
  "Hwang Hee-chan":           "הואנג הי-צ'אן",
  "Jo Hyeon-woo":             "ג'ו היאון-וו",
  "Kim Seung-gyu":            "קים סונג-גיו",
  "Song Bum-keun":            "סונג בום-קון",
  "Kim Min-jae":              "קים מין-ג'ה",
  "Cho Yu-min":               "צ'ו יו-מין",
  "Yang Hyun-jun":            "יאנג היון-ג'ון",
  "Hwang In-beom":            "הואנג אין-בום",
  "Bae Jun-ho":               "ביי ג'ון-הו",
  "Eom Ji-sung":              "אום ג'י-סונג",
  "Lee Jae-sung":             "לי ג'ה-סונג",
  "Oh Hyeon-gyu":             "או היון-גיו",
  "Lee Dong-gyeong":          "לי דונג-גיאונג",
  "Paik Seung-ho":            "ביק סונג-הו",

  // ── URUGUAY (Group H) ───────────────────────────────────────────────────────
  "Federico Valverde":        "פדריקו וולבדה",
  "Darwin Núñez":             "דרווין נוניס",
  "Darwin Nunez":             "דרווין נוניס",
  "Ronald Araújo":            "רונלד אראוחו",
  "Ronald Araujo":            "רונלד אראוחו",
  "José María Giménez":       "חוזה מריה חימנס",
  "Jose Maria Gimenez":       "חוזה מריה חימנס",
  "Fernando Muslera":         "פרנאנדו מוסלרה",
  "Manuel Ugarte":            "מנואל אוגרטה",
  "Rodrigo Bentancur":        "רודריגו בנטנקור",
  "Santiago Bueno":           "סנטיאגו בואנו",
  "Mathías Olivera":          "מתיאס אוליברה",
  "Mathias Olivera":          "מתיאס אוליברה",
  "Martín Cáceres":           "מרטין קאסרס",
  "Martin Caceres":           "מרטין קאסרס",
  "Facundo Torres":           "פקונדו טורס",
  "Giorgian De Arrascaeta":   "ג'יורג'יאן דה ארסקאטה",
  "Agustín Canobbio":         "אגוסטין קנוביו",
  "Agustin Canobbio":         "אגוסטין קנוביו",
  "Nicolás De La Cruz":       "ניקולאס דה לה קרוס",
  "Nicolas De La Cruz":       "ניקולאס דה לה קרוס",
  "Sebastián Cáceres":        "סבסטיאן קאסרס",
  "Sebastian Caceres":        "סבסטיאן קאסרס",

  // ── COLOMBIA (Group K) ──────────────────────────────────────────────────────
  "Luis Díaz":                "לואיס דיאס",
  "Luis Diaz":                "לואיס דיאס",
  "James Rodríguez":          "חיימס רודריגס",
  "James Rodriguez":          "חיימס רודריגס",
  "David Ospina":             "דיוויד אוספינה",
  "Davinson Sánchez":         "דוינסון סנצ'ס",
  "Davinson Sanchez":         "דוינסון סנצ'ס",
  "Yerry Mina":               "ירי מינה",
  "Daniel Muñoz":             "דניאל מוניוס",
  "Daniel Munoz":             "דניאל מוניוס",
  "Santiago Arias":           "סנטיאגו אריאס",
  "Jhon Lucumí":              "ג'ון לוקומי",
  "Jhon Lucumi":              "ג'ון לוקומי",
  "Gustavo Puerta":           "גוסטבו פואגה",
  "Jefferson Lerma":          "ג'פרסון לרמה",
  "Jhon Arias":               "ג'ון אריאס",
  "Jorge Carrascal":          "חורחה קרסקל",
  "Juan Fernando Quintero":   "חואן פרנאנדו קינטרו",
  "Richard Ríos":             "ריצ'ארד ריוס",
  "Richard Rios":             "ריצ'ארד ריוס",
  "Juan Camilo Hernández":    "חואן קמילו הרנדס",
  "Juan Camilo Hernandez":    "חואן קמילו הרנדס",
  "Jhon Córdoba":             "ג'ון קורדובה",
  "Jhon Cordoba":             "ג'ון קורדובה",

  // ── SAUDI ARABIA (Group H) ──────────────────────────────────────────────────
  "Mohammed Al-Owais":        "מוחמד אל-עוואיס",
  "Saud Abdulhamid":          "סעוד עבדאלחמיד",
  "Saleh Al-Shehri":          "סאלח אל-שהרי",
  "Mohammed Al-Dawsari":      "מוחמד אל-דוסרי",
  "Salem Al-Dawsari":         "סאלם אל-דוסרי",
  "Hassan Al-Tambakti":       "חסן אל-תמבאקטי",
  "Firas Al-Buraikan":        "פיראס אל-בוריקן",
  "Abdullah Al-Hamdan":       "עבדאללה אל-חמדן",
  "Ali Lajami":               "עלי לג'מי",
  "Nawaf Al-Aqidi":           "נוואף אל-עקידי",
  "Mohamed Kanno":            "מוחמד קנו",
  "Abdullah Al-Khaibari":     "עבדאללה אל-ח'יברי",
  "Nasser Al-Dawsari":        "נאסר אל-דוסרי",

  // ── QATAR (Group B) ─────────────────────────────────────────────────────────
  "Almoez Ali":               "אלמואז עלי",
  "Akram Afif":               "עקרם עפיף",
  "Hassan Al-Haydos":         "חסן אל-חיידוס",
  "Boualem Khoukhi":          "בואלם חוחי",
  "Abdulaziz Hatem":          "עבדאלעזיז חאטם",
  "Karim Boudiaf":            "כרים בודיאף",
  "Mohammed Muntari":         "מוחמד מונטארי",
  "Assim Madibo":             "עאסם מדיבו",
  "Pedro Miguel":             "פדרו מיגל",
  "Edmilson Junior":          "אדמילסון ג'וניור",

  // ── SWITZERLAND (Group B) ───────────────────────────────────────────────────
  "Granit Xhaka":             "גרניט שאקה",
  "Yann Sommer":              "יאן זומר",
  "Ricardo Rodríguez":        "ריקארדו רודריגס",
  "Ricardo Rodriguez":        "ריקארדו רודריגס",
  "Manuel Akanji":            "מנואל אקנג'י",
  "Nico Elvedi":              "ניקו אלבדי",
  "Silvan Widmer":            "סילוון וידמר",
  "Breel Embolo":             "בריל אמבולו",
  "Remo Freuler":             "רמו פרוילר",
  "Denis Zakaria":            "דניס זקריה",
  "Ruben Vargas":             "רובן ווארגס",
  "Dan Ndoye":                "דן נדויה",
  "Zeki Amdouni":             "זקי אמדוני",
  "Noah Okafor":              "נוה אוקאפור",
  "Ardon Jashari":            "ארדון ג'שארי",
  "Fabian Rieder":            "פביאן רידר",
  "Michel Aebischer":         "מישל איביסר",

  // ── EGYPT (Group G) ─────────────────────────────────────────────────────────
  "Mohamed Salah":            "מוחמד סאלח",
  "Mohamed Elneny":           "מוחמד אל-ננני",
  "Mostafa Mohamed":          "מוסטפה מוחמד",
  "Ahmed Hegazi":             "אחמד הגאזי",
  "Omar Marmoush":            "עומר מרמוש",
  "Trézéguet":                "טרזגה",
  "Trezeguet":                "טרזגה",
  "Mohamed Abou Gabal":       "מוחמד אבו גבל",
  "Ramadan Sobhi":            "רמדאן סובחי",
  "Ahmed El-Shenawy":         "אחמד אל-שנאווי",

  // ── GHANA (Group L) ─────────────────────────────────────────────────────────
  "Thomas Partey":            "תומס פרטיי",
  "André Ayew":               "אנדרה אייו",
  "Andre Ayew":               "אנדרה אייו",
  "Jordan Ayew":              "ג'ורדן אייו",
  "Mohammed Kudus":           "מוחמד קודוס",
  "Inaki Williams":           "אינאקי ויליאמס",
  "Joseph Aidoo":             "ג'וזף אידו",
  "Lawrence Ati-Zigi":        "לורנס אטי-זיגי",
  "Tariq Lamptey":            "טריק למפטי",
  "Osman Bukari":             "עות'מן בוקארי",

  // ── IVORY COAST (Group E) ───────────────────────────────────────────────────
  "Didier Drogba":            "דידייה דרוגבה",
  "Sébastien Haller":         "סבסטיאן הלר",
  "Sebastien Haller":         "סבסטיאן הלר",
  "Franck Kessié":            "פרנק קסיה",
  "Franck Kessie":            "פרנק קסיה",
  "Serge Aurier":             "סרז' אוריה",
  "Eric Bailly":              "אריק ביילי",
  "Wilfried Zaha":            "וילפריד זאהה",
  "Nicolas Pépé":             "ניקולה פפה",
  "Nicolas Pepe":             "ניקולה פפה",
  "Simon Adingra":            "סיימון אדינגרה",
  "Emerse Faé":               "אמרס פה",

  // ── NORWAY (Group I — note: Haaland) ────────────────────────────────────────
  "Erling Haaland":           "ארלינג האלנד",
  "Martin Ødegaard":          "מרטין אדגור",
  "Martin Odegaard":          "מרטין אדגור",
  "Alexander Sørloth":        "אלכסנדר סורלות",
  "Alexander Sorloth":        "אלכסנדר סורלות",
  "Antonio Nusa":             "אנטוניו נוסה",
  "Sander Berge":             "סנדר ברגה",
  "Stefan Strandberg":        "סטפן שטרנדברג",
  "Rúnar Alex Rúnarsson":     "רונאר אלקס רונרסון",

  // ── SWEDEN (Group F) ────────────────────────────────────────────────────────
  "Alexander Isak":           "אלכסנדר איסאק",
  "Victor Lindelöf":          "ויקטור לינדלוף",
  "Victor Lindelof":          "ויקטור לינדלוף",
  "Emil Forsberg":            "אמיל פורסברג",
  "Dejan Kulusevski":         "דיאן קולוסבסקי",
  "Robin Olsen":              "רובין אולסן",
  "Marcus Danielson":         "מרקוס דניאלסון",
  "Ludwig Augustinsson":      "לודוויג אוגוסטינסון",
  "Zlatan Ibrahimović":       "זלאטן איברהימוביץ",
  "Zlatan Ibrahimovic":       "זלאטן איברהימוביץ",

  // ── ECUADOR (Group E) ───────────────────────────────────────────────────────
  "Enner Valencia":           "אנר ולנסיה",
  "Gonzalo Plata":            "גונסאלו פלאטה",
  "Moisés Caicedo":           "מויסס קייסדו",
  "Moises Caicedo":           "מויסס קייסדו",
  "Ángel Mena":               "אנחל מנה",
  "Angel Mena":               "אנחל מנה",
  "Pervis Estupiñán":         "פרביס אסטופיניאן",
  "Pervis Estupinan":         "פרביס אסטופיניאן",
  "Jeremy Sarmiento":         "ג'רמי סרמיינטו",
  "Piero Hincapié":           "פיירו אינקפייה",
  "Piero Hincapie":           "פיירו אינקפייה",

  // ── IRAN (Group G) ──────────────────────────────────────────────────────────
  "Mehdi Taremi":             "מהדי תרמי",
  "Sardar Azmoun":            "סרדר אזמון",
  "Alireza Jahanbakhsh":      "עלירזה ג'אהנבחש",
  "Milad Mohammadi":          "מילאד מוחמדי",
  "Ali Gholizadeh":           "עלי ח'וליזאדה",
  "Saman Ghoddos":            "סאמן ח'ודוס",
  "Karim Ansarifard":         "כרים אנסריפרד",
  "Roozbeh Cheshmi":          "רוזבה צ'שמי",
  "Amir Abedzadeh":           "אמיר עבדזאדה",

  // ── AUSTRIA (Group J) ───────────────────────────────────────────────────────
  "David Alaba":              "דיוויד אלבה",
  "Marcel Sabitzer":          "מרסל זאביצר",
  "Christoph Baumgartner":    "כריסטוף באומגרטנר",
  "Konrad Laimer":            "קונראד ליימר",
  "Michael Gregoritsch":      "מיכאל גרגוריטש",
  "Marko Arnautović":         "מרקו ארנאוטוביץ",
  "Marko Arnautovic":         "מרקו ארנאוטוביץ",
  "Patrick Pentz":            "פטריק פנץ",
  "Stefan Posch":             "שטפן פוש",

  // ── ALGERIA (Group J) ───────────────────────────────────────────────────────
  "Riyad Mahrez":             "ריאד מהרז",
  "Islam Slimani":            "איסלם סלימאני",
  "Youcef Atal":              "יוסף עטאל",
  "Andy Delort":              "אנדי דלור",
  "Nabil Bentaleb":           "נביל בנטאלב",
  "Ismail Bennacer":          "ישמעיל בנאסר",
  "Saïd Benrahma":            "סעיד בן-ראחמה",
  "Said Benrahma":            "סעיד בן-ראחמה",

  // ── TUNISIA (Group F) ───────────────────────────────────────────────────────
  "Wahbi Khazri":             "ווהבי חזרי",
  "Ellyes Skhiri":            "אליס שקירי",
  "Hannibal Mejbri":          "חניבעל מג'ברי",
  "Youssef Msakni":           "יוסף מסכני",
  "Ali Maaloul":              "עלי מעלול",

  // ── IRAQ (Group I) ──────────────────────────────────────────────────────────
  "Mohanad Ali":              "מוחנד עלי",
  "Amjad Attwan":             "אמג'ד עטוואן",
  "Aymen Hussein":            "איימן חוסין",

  // ── SCOTLAND (Group C) ──────────────────────────────────────────────────────
  "Andy Robertson":           "אנדי רוברטסון",
  "Scott McTominay":          "סקוט מקטומיניי",
  "Che Adams":                "צ'ה אדמס",
  "John McGinn":              "ג'ון מקגין",
  "Callum McGregor":          "קאלום מקגרגור",
  "Ryan Christie":            "ריאן כריסטי",
  "Lawrence Shankland":       "לורנס שנקלנד",
  "Stuart Armstrong":         "סטוארט ארמסטרונג",
  "Kenny McLean":             "קני מקלין",
  "Ryan Jack":                "ריאן ג'ק",

  // ── PANAMA (Group L) ────────────────────────────────────────────────────────
  "Rodolfo Pizarro":          "רודולפו פיסארו",
  "Rolando Blackburn":        "רולנדו בלקברן",
  "Cecilio Waterman":         "ססיליו ווטרמן",
  "Adalberto Carrasquilla":   "אדלברטו קרסקיה",
  "Fidel Escobar":            "פידל אסקובר",
  "José Luis Rodríguez":      "חוזה לואיס רודריגס",

  // ── BOLIVIA (did not qualify — kept for reference) ──────────────────────────
  // ── NEW ZEALAND (Group G) ───────────────────────────────────────────────────
  "Chris Wood":               "כריס וווד",
  "Ryan Thomas":              "ריאן תומס",
  "Clayton Lewis":            "קלייטון לואיס",

  // ── SOUTH AFRICA (Group A) ──────────────────────────────────────────────────
  "Percy Tau":                "פרסי טאו",
  "Bongani Zungu":            "בונגאני זונגו",
  "Themba Zwane":             "תמבה זוואנה",
  "Ronwen Williams":          "רונוון ויליאמס",
  "Rushine De Reuck":         "ראשין דה רוק",

  // ── BOSNIA-HERZEGOVINA (Group B) ────────────────────────────────────────────
  "Edin Džeko":               "אדין ד'קו",
  "Edin Dzeko":               "אדין ד'קו",
  "Miralem Pjanić":           "מיראלם פיאניץ",
  "Miralem Pjanic":           "מיראלם פיאניץ",
  "Sead Kolašinac":           "סעד קולשינץ",
  "Sead Kolasinac":           "סעד קולשינץ",
  "Vedran Ćorluka":           "ודראן צ'ורלוקה",

  // ── CZECH REPUBLIC (Group A) ────────────────────────────────────────────────
  "Tomáš Souček":             "תומאש סוצ'ק",
  "Tomas Soucek":             "תומאש סוצ'ק",
  "Patrik Schick":            "פטריק שיק",
  "Vladimír Coufal":          "ולאדימיר קאופאל",
  "Vladimir Coufal":          "ולאדימיר קאופאל",
  "Ondřej Kolář":             "אונדרז'י קולר",
  "Ondrej Kolar":             "אונדרז'י קולר",
  "Lukáš Provod":             "לוקאש פרובוד",
  "Adam Hložek":              "אדם חלוז'ק",
  "Adam Hlozek":              "אדם חלוז'ק",

  // ── PARAGUAY (Group D) ──────────────────────────────────────────────────────
  "Miguel Almirón":           "מיגל אלמירון",
  "Miguel Almiron":           "מיגל אלמירון",
  "Robert Morales":           "רוברט מוראלס",
  "Gustavo Gómez":            "גוסטבו גומס",
  "Gustavo Gomez":            "גוסטבו גומס",
  "Ángel Romero":             "אנחל רומרו",
  "Angel Romero":             "אנחל רומרו",

  // ── TURKEY (Group D) ────────────────────────────────────────────────────────
  "Arda Güler":               "ארדה גולר",
  "Arda Guler":               "ארדה גולר",
  "Hakan Çalhanoğlu":         "האקן צ'לחנאולו",
  "Hakan Calhanoglu":         "האקן צ'לחנאולו",
  "Cengiz Ünder":             "גנגיז אונדר",
  "Cengiz Under":             "גנגיז אונדר",
  "Merih Demiral":            "מריח דמירל",
  "Burak Yılmaz":             "בוראק יילמאז",
  "Burak Yilmaz":             "בוראק יילמאז",
  "Kenan Yıldız":             "כנאן יילדיז",
  "Kenan Yildiz":             "כנאן יילדיז",
  "Ferdi Kadıoğlu":           "פרדי קדיאולו",
  "Ferdi Kadioglu":           "פרדי קדיאולו",
  "Mert Günok":               "מרט גונוק",
  "Mert Gunok":               "מרט גונוק",

  // ── DR CONGO (Group K) ──────────────────────────────────────────────────────
  "Chancel Mbemba":           "שנסל מבמבה",
  "Yannick Bolasie":          "יאניק בולאסי",
  "Arthur Masuaku":           "ארתור מסואקו",

  // ── UZBEKISTAN (Group K) ────────────────────────────────────────────────────
  "Eldor Shomurodov":         "אלדור שומורודוב",
  "Abbosbek Fayzullaev":      "אבוסבק פאיזולאיב",
  "Otabek Shamsiev":          "אוטאבק שמסיב",

  // ── CAPE VERDE (Group H) ────────────────────────────────────────────────────
  "Garry Rodrigues":          "גארי רודריגס",
  "Nuno Borges":              "נונו בורגס",
  "Ryan Mendes":              "ריאן מנדס",

  // ── HAITI (Group C) ─────────────────────────────────────────────────────────
  "Nazon Duckens":            "נזון דוקנס",

  // ── JORDAN (Group J) ────────────────────────────────────────────────────────
  "Ahmad Hayel":              "אחמד חייל",
  "Mahmoud Alrasheed":        "מחמוד אל-ראשיד",

  // Extra notable names that commonly appear in Israeli football coverage:
  "Karim Benzema":            "כרים בנזמה",
  "Olivier Giroud":           "אוליבייה ז'ירו",
  "Didier Deschamps":         "דידייה דשאן",
  "Pep Guardiola":            "פפ גווארדיולה",
  "Luis Enrique":             "לואיס אנריקה",
  "Carlo Ancelotti":          "קרלו אנצ'לוטי",
  "Julian Nagelsmann":        "יוליאן נגלסמן",
  "Thomas Tuchel":            "תומס טוכל",
  "Zinedine Zidane":          "זינדין זידאן",
  "Roberto Martínez":         "רוברטו מרטינס",
  "Roberto Martinez":         "רוברטו מרטינס",
  "Lionel Scaloni":           "ליונל סקאלוני",
  "Marcelo Bielsa":           "מרסלו בייסה",
  "Jesse Marsch":             "ג'סי מארש",
  "Mauricio Pochettino":      "מאוריסיו פוצ'טינו",
  "Javier Aguirre":           "חבייר אגירה",
};

/**
 * Look up Hebrew name for a player.
 * Falls back to the original English name if not found.
 * @param {string} englishName
 * @returns {string}
 */
export function getPlayerNameHe(englishName) {
  if (!englishName) return englishName;
  return PLAYER_NAME_HE[englishName] ?? englishName;
}

/**
 * Try to find a Hebrew name by partial match (useful for API name variants).
 * @param {string} apiName — name from external API (may have accents stripped)
 * @returns {string|null}
 */
export function findPlayerNameHe(apiName) {
  if (!apiName) return null;
  const norm = s => s.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "");
  const normalised = norm(apiName);
  for (const [eng, heb] of Object.entries(PLAYER_NAME_HE)) {
    if (norm(eng) === normalised) return heb;
  }
  return null;
}
